/// A destination's flag, built from its own code — no lookup table typed
/// by hand, no bundled image, no network call.
///
/// The catalogue's country codes are ISO 3166-1 **alpha-3** end to end —
/// Store rows, a pack's coverage list, `place_names.g.dart`'s search index,
/// this project's own test fixtures (`DZA`, `AUT`, ...). An earlier version
/// of this file claimed alpha-2 via a `Destination.fromCountry` constructor
/// that does not exist — running [countryFlagEmoji] against the real
/// catalogue proved it wrong (every call returned null) before it shipped
/// anywhere the fallback wouldn't have hidden it. Corrected here.
///
/// A flag EMOJI is only defined for an alpha-2 pair of Unicode "regional
/// indicator symbol" characters, so alpha-3 is normalised to alpha-2 first —
/// via [kAlpha3ToAlpha2] (`country_codes.g.dart`, generated by
/// `tool/gen_place_names.dart` from the same CLDR `codeMappings.json` that
/// generator already loads for `country_names.g.dart`), not a second,
/// hand-typed table that could drift from the first. Nothing here fetches:
/// the map ships in the build, same as the names it sits beside.
///
/// The old app pulled every flag from `flagcdn.com` at runtime — an
/// uncontrolled third-party dependency in a commercial funnel (rebuild
/// audit, `country.dart:75,77`). [DestinationTile]'s tinted letter-disc
/// replaced that with a coloured circle carrying the code itself: honest,
/// but not a flag. This closes that gap without reopening the dependency —
/// two characters of Dart source, still zero network.
///
/// The one honest trade-off, unrelated to alpha-2/alpha-3: flag-emoji
/// rendering depends on the *system* font, not one of this app's own
/// bundled families (see [AppType] — its fallback chain is deliberately
/// narrow, Arabic only, and does not cover emoji). iOS has rendered coloured
/// flag emoji reliably for years; a minority of older or heavily customised
/// Android builds still show two letters instead of a flag. [countryFlagEmoji]
/// can't detect that — callers fall back to their existing glyph regardless
/// of why it returned null.
library;

import 'country_codes.g.dart';
import 'country_flag_assets.g.dart';
import 'country_colors.g.dart';
import 'country_flag_maps.g.dart';

const int _regionalIndicatorBase = 0x1F1E6; // Unicode regional indicator 'A'
const int _asciiA = 0x41;
const int _asciiZ = 0x5A;

/// The flag emoji for a country code from this catalogue — alpha-3
/// (`"DZA"`, `"fra"`, the format `destination.code` actually carries) or
/// alpha-2, either case. Returns `null` for a regional/global pack
/// pseudo-code, an alpha-3 [kAlpha3ToAlpha2] doesn't cover, or anything else
/// that isn't a resolvable country code. Callers fall back to their existing
/// glyph in that case, the same way [DestinationTile] falls back to the code
/// itself today.
String? countryFlagEmoji(String code) {
  final alpha2 = _alpha2(code);
  if (alpha2 == null) return null;
  final a = alpha2.codeUnitAt(0);
  final b = alpha2.codeUnitAt(1);
  if (a < _asciiA || a > _asciiZ || b < _asciiA || b > _asciiZ) return null;
  return String.fromCharCodes(<int>[
    _regionalIndicatorBase + (a - _asciiA),
    _regionalIndicatorBase + (b - _asciiA),
  ]);
}

/// The bundled SVG for a country code, or `null` when this catalogue code
/// has no flag to draw.
///
/// The flags themselves are real artwork now (`assets/flags/`, from
/// lipis/flag-icons), not the two regional-indicator characters above. The
/// emoji were a way to show a flag without bundling 257 of them, and they
/// cost what that saved: rendering depended on a system font this app does
/// not control, Noto draws every flag as a *waving* rectangle so the corners
/// of a round badge stayed empty, and a minority of Android builds showed
/// two letters instead. An asset renders the same on every device, at any
/// size, and still needs no network — which was the point of dropping
/// flagcdn.com in the first place.
///
/// [countryFlagEmoji] stays for text contexts, where an inline character is
/// the only thing that composes with a sentence.
String? countryFlagAsset(String code) {
  final alpha2 = _alpha2(code)?.toLowerCase();
  if (alpha2 == null || !kFlagAssetCodes.contains(alpha2)) return null;
  return 'assets/flags/$alpha2.svg';
}

/// A catalogue code — alpha-3 (`"DZA"`, what `destination.code` carries) or
/// alpha-2, either case — as an upper-case alpha-2 pair, or `null` for a
/// regional/global pack pseudo-code and anything else that isn't a country.
String? _alpha2(String code) {
  final upper = code.trim().toUpperCase();
  final alpha2 = switch (upper.length) {
    2 => upper,
    3 => kAlpha3ToAlpha2[upper],
    _ => null,
  };
  return alpha2 != null && alpha2.length == 2 ? alpha2 : null;
}

/// The DESTINATION's own identity colour — Austria red, Italy green — or
/// `null` when this code has no flag to derive one from.
///
/// Derived from the bundled flag at build time (`country_colors.g.dart`), so
/// it costs nothing at runtime and needs no per-country configuration. It is
/// deliberately NOT a brand token: this is the one colour on a destination
/// card that must stay the same in every white-label app, while the text,
/// button and pills beside it all come from `AppTokens`.
int? countryColorValue(String code) {
  final alpha2 = _alpha2(code)?.toLowerCase();
  return alpha2 == null ? null : kCountryColors[alpha2];
}

/// The bundled flag-map for a country — its outline filled with its own flag
/// — or `null` when it has none.
///
/// 90 of the catalogue's ~200 destinations have one; the rest fall back to
/// the plain silhouette in `country_shapes.g.dart`. The list is curated by
/// hand (`country_flag_maps.g.dart`) rather than matched at runtime, because
/// the source art includes historical and disputed maps that must never
/// reach a card.
String? countryFlagMapAsset(String code) {
  final alpha2 = _alpha2(code)?.toLowerCase();
  if (alpha2 == null || !kFlagMapSources.containsKey(alpha2)) return null;
  return 'assets/flag_maps/$alpha2.svg';
}
