/// Rewrites the per-brand asset entries in `pubspec.yaml`, between its
/// `BEGIN brand flavors` / `END brand flavors` markers: two entries for every
/// folder under `brands/` holding a brand.json, and nothing else.
///
/// ```
/// dart run tool/gen_brand_flavors.dart
/// ```
///
/// Each brand ships its brand.json and its assets folder into its own flavor
/// only. Miss one entry and every client ships every other client's files,
/// which is why they are generated rather than typed, and why
/// brand_wiring_test fails until this has been run for a new brand. Running it
/// again changes nothing.
library;

import 'dart:io';

const _begin = '    # BEGIN brand flavors: generated by tool/gen_brand_flavors.dart, do not edit';
const _end = '    # END brand flavors';

/// [pubspec] with the block between the markers replaced by the entries of
/// [slugs], in that order.
String withBrandFlavors(String pubspec, List<String> slugs) {
  final start = pubspec.indexOf(_begin);
  final end = pubspec.indexOf(_end);
  if (start < 0 || end < start) {
    throw StateError('pubspec.yaml has lost its brand flavors markers:\n$_begin\n$_end');
  }
  final entries = [
    for (final slug in slugs)
      for (final path in ['brands/$slug/brand.json', 'brands/$slug/assets/'])
        '    - path: $path\n      flavors: [$slug]\n',
  ].join();
  return '${pubspec.substring(0, start)}$_begin\n$entries${pubspec.substring(end)}';
}

/// The folders under `<root>/brands/` holding a brand.json, sorted: the same
/// list Gradle builds flavors from.
List<String> brandSlugs([String root = '.']) => [
      for (final dir in Directory('$root/brands').listSync().whereType<Directory>())
        if (File('${dir.path}/brand.json').existsSync())
          dir.uri.pathSegments.where((s) => s.isNotEmpty).last,
    ]..sort();

void main() {
  final slugs = brandSlugs();
  final pubspec = File('pubspec.yaml');
  final before = pubspec.readAsStringSync();
  final after = withBrandFlavors(before, slugs);
  if (after == before) {
    stdout.writeln('pubspec.yaml: brand flavors up to date (${slugs.join(', ')})');
  } else {
    pubspec.writeAsStringSync(after);
    stdout.writeln('pubspec.yaml: brand flavors rewritten for ${slugs.join(', ')}');
  }
}
