// SPC Studio, Assets tab. Each drop zone previews what its file becomes, and
// Save writes that file only. The icon set is written by "Regenerate assets"
// alone, so a published brand's hand-made icons stay until someone asks.
'use strict';

const LABELS = {
  mark: ['Logo mark', 'Square PNG, 432 px or more. The launcher and app icons are made from it.'],
  full: ['Full logo', 'The lockup on light grounds. PNG, up to 2048 px wide.'],
  fullInverse: ['Inverse logo', 'The lockup on dark grounds. PNG, up to 2048 px wide.'],
  intro: ['Intro video', 'MP4, video only, about 4 s and under 3 MB: it must start within 1.5 s.'],
  card: ['Card background', 'Behind the destination cards. JPEG, up to 2832 px wide.'],
};
const ACCEPT = { intro: 'video/mp4', card: 'image/jpeg,image/png' };

let assetState = null;
let pending = null; // {slot, file, data, credit, strip}

function raw(path) {
  return `/api/brands/${state.slug}/raw?path=${encodeURIComponent(path)}`;
}

async function renderAssets() {
  const slug = state.slug;
  $('side-plan').replaceChildren(el('p', 'none', 'Drop a file on a slot to preview what it becomes.'));
  const view = $('view-assets');
  view.replaceChildren(el('p', 'none', 'Loading…'));
  assetState = (await api(`/api/brands/${slug}/assets`)).data;
  if (slug !== state.slug || state.view !== 'assets') return;
  pending = null;

  const head = el('div', 'sheet-head');
  head.append(el('h1', '', current().name ?? slug));
  if (edited(slug)) head.append(el('span', 'chip warn', 'Brand tab has unsaved edits: apply or revert them first'));

  // The icon set as it is now, under each mask.
  const icons = el('section', 'asset-group');
  const mark = assetState.icons.find((i) => i.path.endsWith('drawable/brand_mark.png'));
  const made = assetState.icons.filter((i) => i.exists).length;
  icons.append(el('h2', 'label', `Icon set · ${made} of ${assetState.icons.length} files · ${assetState.generatedIcons ? 'generated by Studio' : 'hand-made'}`));
  if (mark?.exists) icons.append(maskTiles({ mark: raw(mark.path), bg: assetState.launch }));
  const regen = el('button', 'ghost', 'Preview “Regenerate assets”');
  regen.type = 'button';
  regen.onclick = previewIcons;
  icons.append(el('p', 'plan-note', 'Built from the logo mark: brand_mark (432 px, inside the safe zone), the themed-icon layer, launcher mipmaps 48–192, notification icons 24–96, the iOS AppIcon 1024 without alpha. Written only when you press Regenerate.'), regen);

  const groups = [
    ['Logos', ['mark', 'full', 'fullInverse']],
    ['Intro', ['intro']],
    ['Card background', ['card']],
    ['Pack images · 1200×675, a source and a licence each', assetState.slots.filter((s) => s.slot.startsWith('pack:')).map((s) => s.slot)],
  ];
  const sections = groups.map(([title, ids]) => {
    const s = el('section', 'asset-group');
    s.append(el('h2', 'label', title));
    const grid = el('div', 'slots');
    grid.append(...ids.map(slotCard));
    if (title.startsWith('Pack')) grid.append(overrideCard());
    s.append(grid);
    return s;
  });
  view.replaceChildren(head, icons, ...sections);
}

function slotCard(id) {
  const s = assetState.slots.find((x) => x.slot === id) ?? { slot: id, exists: false };
  const pack = id.startsWith('pack:');
  const [title, hint] = pack ? [id.slice(5), 'Cropped to 16:9.'] : LABELS[id];
  const card = el('div', 'slot');
  card.dataset.slot = id;
  card.append(el('h3', '', title), el('p', 'hint', hint));
  if (s.exists && id !== 'intro') {
    const img = el('img', 'current');
    img.src = raw(s.path);
    img.alt = `current ${title}`;
    card.append(img);
  }
  card.append(el('p', 'meta', s.exists ? `${s.name} · ${kb(s.bytes)}` : 'none yet'));
  let credit = null;
  if (pack) {
    credit = el('div', 'credit');
    for (const [k, label] of [['source', 'Source (URL or name)'], ['licence', 'Licence, e.g. CC0'], ['author', 'Author (optional)']]) {
      const i = el('input');
      i.type = 'text';
      i.placeholder = label;
      i.dataset.k = k;
      i.setAttribute('aria-label', `${title} ${label}`);
      credit.append(i);
    }
    card.append(credit);
  }
  card.append(dropZone(s.exists ? 'Drop a replacement' : 'Drop a file', ACCEPT[id] ?? 'image/png,image/jpeg', async (file) => {
    const creditValues = credit ? Object.fromEntries([...credit.querySelectorAll('input')].map((i) => [i.dataset.k, i.value])) : {};
    pending = { slot: id, file: file.name, data: await fileToBase64(file), credit: creditValues, strip: false };
    previewSlot();
  }));
  return card;
}

/// A country that gets its own picture instead of its region's.
function overrideCard() {
  const card = el('div', 'slot');
  card.append(el('h3', '', 'Country override'), el('p', 'hint', 'ISO3 code, e.g. TUR. Then drop its picture.'));
  const code = el('input');
  code.type = 'text';
  code.maxLength = 3;
  code.placeholder = 'ISO3';
  code.setAttribute('aria-label', 'country override ISO3 code');
  const add = el('button', 'ghost', 'Add');
  add.type = 'button';
  add.onclick = () => {
    const iso = code.value.trim().toUpperCase();
    if (!/^[A-Z]{3}$/.test(iso)) return;
    if (!assetState.slots.some((s) => s.slot === `pack:${iso}`)) {
      assetState.slots.push({ slot: `pack:${iso}`, exists: false });
    }
    card.before(slotCard(`pack:${iso}`));
    code.value = '';
  };
  const row = el('div', 'credit');
  row.append(code, add);
  card.append(row);
  return card;
}

async function previewSlot(acceptDirty) {
  if (!pending) return;
  const slug = state.slug;
  if (edited(slug)) {
    renderPlan({ errors: [{ field: 'brand.json', reason: 'the Brand tab has unsaved edits: apply or revert them first' }], warnings: [], notes: [], changes: [], files: [] },
      { title: `${pending.file} → ${pending.slot}`, applyLabel: 'Save', onApply: () => {} });
    return;
  }
  // The credit can be typed after the drop: read it again each time.
  const card = document.querySelector(`.slot[data-slot="${CSS.escape(pending.slot)}"]`);
  if (card?.querySelector('.credit input[data-k]')) {
    pending.credit = Object.fromEntries([...card.querySelectorAll('.credit input[data-k]')].map((i) => [i.dataset.k, i.value]));
  }
  const body = { slot: pending.slot, data: pending.data, credit: pending.credit, strip: pending.strip };
  const { data } = await api(`/api/brands/${slug}/assets/preview`, body);
  if (slug !== state.slug) return;
  let extra = null;
  if (data.notes.includes('strip-available')) {
    extra = el('button', 'ghost', 'Strip the audio track with ffmpeg');
    extra.type = 'button';
    extra.onclick = () => { pending.strip = true; previewSlot(); };
  }
  if (card?.querySelector('.credit input[data-k]')) {
    const again = el('button', 'ghost', 'Re-check with the credit as typed');
    again.type = 'button';
    again.onclick = () => previewSlot();
    extra = extra ?? again;
  }
  renderPlan(data, {
    title: `${pending.file} → ${pending.slot}`,
    applyLabel: 'Save',
    dirty: acceptDirty,
    extra,
    onApply: (accepted) => saveSlot(accepted),
  });
}

async function saveSlot(acceptDirty) {
  const slug = state.slug;
  const body = { slot: pending.slot, data: pending.data, credit: pending.credit, strip: pending.strip, acceptDirty };
  const { status: code, data } = await api(`/api/brands/${slug}/assets/apply`, body);
  if (code === 409) return previewSlot(data.dirty);
  if (code !== 200) return planStatus(data.refused || data.error, true);
  await load(slug); // brand.json may name the new file
  renderProof();
  renderRail();
  await renderAssets();
  planStatus(`Wrote ${data.written.length} file${data.written.length === 1 ? '' : 's'}. Review and commit when ready.`);
}

async function previewIcons(acceptDirty) {
  const slug = state.slug;
  const { data } = await api(`/api/brands/${slug}/icons/preview`, {});
  if (slug !== state.slug) return;
  renderPlan(data, {
    title: `Regenerate assets · ${current().name}`,
    applyLabel: `Regenerate assets for ${current().name}`,
    dirty: Array.isArray(acceptDirty) ? acceptDirty : undefined,
    onApply: async (accepted) => {
      const r = await api(`/api/brands/${slug}/icons/apply`, { acceptDirty: accepted });
      if (r.status === 409) return previewIcons(r.data.dirty);
      if (r.status !== 200) return planStatus(r.data.refused || r.data.error, true);
      await renderAssets();
      planStatus(`Wrote ${r.data.written.length} files. Review and commit when ready.`);
    },
  });
}
